<?php
declare(strict_types=1);
require_once __DIR__ . '/layout.php';
require_admin();

$configs = [
 'menus'=>['title'=>'مدیریت منوها','fields'=>['title'=>'عنوان','link'=>'لینک','icon'=>'آیکون','parent'=>'والد']],
 'sections'=>['title'=>'مدیریت سکشن‌های صفحه اصلی','fields'=>['title'=>'عنوان','slug'=>'اسلاگ','description'=>'توضیح']],
 'hero'=>['title'=>'هیرو صفحه اصلی','single'=>true,'fields'=>['eyebrow'=>'عنوان کوچک','title'=>'تیتر اصلی','description'=>'توضیح اصلی','image'=>'تصویر اصلی','mobile_image'=>'تصویر موبایل','image_alt'=>'alt تصویر','button_1_text'=>'متن دکمه اول','button_1_link'=>'لینک دکمه اول','button_1_action'=>'عملکرد دکمه اول','button_2_text'=>'متن دکمه دوم','button_2_link'=>'لینک دکمه دوم','button_3_text'=>'متن دکمه سوم','button_3_link'=>'لینک دکمه سوم','trust_text'=>'متن اعتمادسازی','cards'=>'کارت‌ها هر خط یک مورد','float_cards'=>'کارت‌های شناور هر خط یک مورد']],
 'challenges'=>['title'=>'چالش‌ها','fields'=>['number'=>'شماره کارت','title'=>'عنوان','description'=>'توضیح','icon'=>'آیکون','image'=>'تصویر']],
 'learning_path'=>['title'=>'مسیر یادگیری','fields'=>['number'=>'شماره مرحله','title'=>'عنوان مرحله','description'=>'توضیح مرحله','icon'=>'آیکون','image'=>'تصویر']],
 'skills'=>['title'=>'مهارت‌های عملی','landing'=>'features','fields'=>['icon'=>'آیکون','title'=>'عنوان مهارت','description'=>'توضیح']],
 'portfolios'=>['title'=>'نمونه‌کارها','landing'=>'projects','fields'=>['title'=>'عنوان نمونه‌کار','slug'=>'اسلاگ','short_description'=>'توضیح کوتاه','description'=>'توضیح کامل','image'=>'تصویر شاخص','gallery'=>'گالری تصاویر، هر خط یک تصویر','category'=>'دسته‌بندی','technologies'=>'تکنولوژی‌ها با کاما','project_url'=>'لینک مشاهده پروژه','demo_url'=>'لینک دمو','github_url'=>'لینک گیت‌هاب','client_name'=>'نام کارفرما','project_date'=>'تاریخ انجام','show_home'=>'نمایش در صفحه اصلی','meta_title'=>'متاتایتل','meta_description'=>'متادیسکریپشن']],
 'portfolio_categories'=>['title'=>'دسته‌بندی نمونه‌کار','fields'=>['title'=>'عنوان','slug'=>'اسلاگ','description'=>'توضیح']],
 'audiences'=>['title'=>'مخاطبان دوره','landing'=>'audience','fields'=>['title'=>'عنوان','description'=>'توضیح','icon'=>'آیکون یا تصویر']],
 'instructor'=>['title'=>'معرفی مدرس','single'=>true,'fields'=>['name'=>'نام مدرس','job_title'=>'عنوان شغلی','short_bio'=>'بیوگرافی کوتاه','description'=>'توضیح کامل','image'=>'تصویر مدرس','mobile_image'=>'تصویر موبایل','trust_features'=>'ویژگی‌های اعتمادسازی هر خط','instagram'=>'اینستاگرام','linkedin'=>'لینکدین','telegram'=>'تلگرام']],
 'courses'=>['title'=>'دوره‌ها','fields'=>['title'=>'عنوان دوره','slug'=>'اسلاگ','instructor'=>'مدرس','short_description'=>'توضیح کوتاه','description'=>'توضیح کامل','image'=>'تصویر دوره','instructor_image'=>'تصویر مدرس','original_price'=>'قیمت اصلی','discount_price'=>'قیمت تخفیفی','currency'=>'واحد پول','discount_badge'=>'برچسب تخفیف','course_type'=>'نوع دوره','course_status'=>'وضعیت دوره','show_home'=>'نمایش در صفحه اصلی','buy_button_text'=>'متن دکمه خرید','consult_button_text'=>'متن دکمه مشاوره','meta_title'=>'متاتایتل','meta_description'=>'متادیسکریپشن']],
 'course_features'=>['title'=>'امکانات دوره','fields'=>['course'=>'انتخاب دوره','title'=>'عنوان امکان','description'=>'توضیح','icon'=>'آیکون']],
 'course_curriculums'=>['title'=>'سرفصل‌های دوره','landing'=>'curriculum','fields'=>['course'=>'انتخاب دوره','title'=>'عنوان فصل','description'=>'توضیح فصل','lessons'=>'لیست درس‌ها هر خط','duration'=>'مدت زمان']],
 'course_results'=>['title'=>'نتایج دوره','landing'=>'results','fields'=>['title'=>'عنوان نتیجه','description'=>'توضیح','icon'=>'آیکون یا تصویر']],
 'testimonials'=>['title'=>'نظرات هنرجوها','landing'=>'testimonials','fields'=>['student_name'=>'نام هنرجو','role'=>'سمت','image'=>'تصویر','text'=>'متن نظر','rating'=>'امتیاز']],
 'faqs'=>['title'=>'سوالات متداول','landing'=>'faqs','fields'=>['question'=>'سوال','answer'=>'پاسخ','category'=>'دسته‌بندی','course'=>'مرتبط با دوره یا عمومی']],
 'ctas'=>['title'=>'CTAها و دکمه‌ها','fields'=>['internal_title'=>'عنوان داخلی','title'=>'عنوان','description'=>'توضیح','button_text'=>'متن دکمه','button_link'=>'لینک دکمه','action'=>'نوع عملکرد','variant'=>'نوع ظاهر','location'=>'محل نمایش']],
 'registrations'=>['title'=>'فرم‌های ثبت‌نام','fields'=>['name'=>'نام و نام خانوادگی','mobile'=>'شماره موبایل','email'=>'ایمیل','level'=>'سطح آشنایی','goal'=>'هدف','description'=>'توضیحات','course'=>'دوره','amount'=>'مبلغ','payment_status'=>'وضعیت پرداخت','follow_status'=>'وضعیت پیگیری','ip'=>'آی‌پی']],
 'consultations'=>['title'=>'درخواست‌های مشاوره','fields'=>['name'=>'نام','mobile'=>'موبایل','message'=>'پیام','goal'=>'هدف کاربر','follow_status'=>'وضعیت پیگیری']],
 'media'=>['title'=>'رسانه‌ها / فایل‌ها','fields'=>['title'=>'عنوان فایل','file'=>'آدرس فایل','alt'=>'alt تصویر','category'=>'دسته‌بندی فایل']],
 'seo'=>['title'=>'تنظیمات سئو','single'=>true,'fields'=>['page'=>'صفحه','title'=>'title','meta_description'=>'meta description','meta_keywords'=>'meta keywords','canonical'=>'canonical','og_title'=>'OG title','og_description'=>'OG description','og_image'=>'OG image','twitter_title'=>'Twitter title','twitter_description'=>'Twitter description','twitter_image'=>'Twitter image','robots'=>'robots']],
 'users'=>['title'=>'کاربران ادمین','fields'=>['name'=>'نام','username'=>'نام کاربری','email'=>'ایمیل','role'=>'نقش']],
];
$section = $_GET['section'] ?? 'sections'; if (!isset($configs[$section])) { http_response_code(404); exit('بخش یافت نشد'); }
$cfg=$configs[$section]; $cms=read_cms_content(); $items=$cms[$section] ?? [];
if ($section==='skills') { $items=array_map(fn($x,$i)=>['id'=>$i+1,'icon'=>$x[0]??'','title'=>$x[1]??'','description'=>$x[2]??'','sort_order'=>$i+1,'status'=>'active'], read_landing_content()['features']??[], array_keys(read_landing_content()['features']??[])); }
$action=$_GET['action']??'list'; $id=(int)($_GET['id']??0);
if ($_SERVER['REQUEST_METHOD']==='POST') { require_csrf();
 if (isset($_POST['delete_id'])) { $did=(int)$_POST['delete_id']; $items=array_values(array_filter($items,fn($i)=>(int)($i['id']??0)!==$did)); $_SESSION['flash']='آیتم حذف شد.'; }
 else { $payload=['id'=>$id ?: next_id($items),'sort_order'=>(int)($_POST['sort_order']??(count($items)+1)),'status'=>($_POST['status']??'active')==='inactive'?'inactive':'active','updated_at'=>gmdate('c')]; foreach($cfg['fields'] as $k=>$label){ $payload[$k]=clean_text($_POST[$k]??'',4000); } if(!$id)$payload['created_at']=gmdate('c'); $found=false; foreach($items as &$it){ if((int)($it['id']??0)===$payload['id']){ $it=array_merge($it,$payload); $found=true; break; }} unset($it); if(!$found)$items[]=$payload; $_SESSION['flash']='اطلاعات ذخیره شد.'; }
 usort($items,fn($a,$b)=>(int)($a['sort_order']??0)<=>(int)($b['sort_order']??0)); $cms[$section]=$items; write_cms_content($cms);
 if (!empty($cfg['landing'])) { $landing=read_landing_content(); $active=active_sorted($items); $key=$cfg['landing']; if($key==='features')$landing[$key]=array_map(fn($i)=>[$i['icon']??'',$i['title']??'',$i['description']??''],$active); elseif($key==='projects')$landing[$key]=array_map(fn($i)=>[$i['title']??'',$i['short_description']??($i['description']??''), array_map('trim',explode(',',$i['technologies']??''))],$active); elseif($key==='audience'||$key==='results'||$key==='testimonials')$landing[$key]=array_map(fn($i)=>$i['title']??($i['text']??''),$active); elseif($key==='curriculum')$landing[$key]=array_map(fn($i)=>[$i['title']??'',$i['description']??''],$active); elseif($key==='faqs')$landing[$key]=array_map(fn($i)=>[$i['question']??'',$i['answer']??''],$active); write_landing_content($landing); }
 redirect('section-manager.php?section='.$section); }
$q=mb_strtolower(clean_text($_GET['q']??'',100),'UTF-8'); $status=$_GET['status']??''; $filtered=array_values(array_filter($items,fn($i)=>($q===''||item_matches_query($i,$q,array_keys($cfg['fields'])))&&($status===''||($i['status']??'active')===$status)));
$edit=null; if($id){ foreach($items as $it){ if((int)($it['id']??0)===$id)$edit=$it; }}
admin_header($cfg['title']);
?>
<section class="admin-card"><div class="section-head"><h2><?= e($cfg['title']) ?></h2><a class="btn btn-primary" href="?section=<?=e($section)?>&action=create"><i class="bi bi-plus"></i> افزودن جدید</a></div>
<form class="row g-2 mb-4"><input type="hidden" name="section" value="<?=e($section)?>"><div class="col-md-5"><input class="form-control" name="q" value="<?=e($q)?>" placeholder="جستجو"></div><div class="col-md-3"><select class="form-select" name="status"><option value="">همه وضعیت‌ها</option><option value="active" <?=$status==='active'?'selected':''?>>فعال</option><option value="inactive" <?=$status==='inactive'?'selected':''?>>غیرفعال</option></select></div><div class="col"><button class="btn btn-outline-primary">فیلتر</button></div></form>
<?php if($action==='create'||$edit): $row=$edit??[]; ?><form method="post" class="row g-3 settings-form"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><?php foreach($cfg['fields'] as $k=>$label): ?><div class="col-md-6"><label class="form-label"><?=e($label)?></label><?php if(in_array($k,['description','text','answer','short_bio','trust_features','cards','float_cards','gallery','lessons'],true)): ?><textarea class="form-control" name="<?=e($k)?>" rows="4"><?=e($row[$k]??'')?></textarea><?php else: ?><input class="form-control" name="<?=e($k)?>" value="<?=e($row[$k]??'')?>"><?php endif; ?></div><?php endforeach; ?><div class="col-md-3"><label class="form-label">ترتیب نمایش</label><input class="form-control" type="number" name="sort_order" value="<?=e($row['sort_order']??(count($items)+1))?>"></div><div class="col-md-3"><label class="form-label">وضعیت</label><select class="form-select" name="status"><option value="active">فعال</option><option value="inactive" <?=($row['status']??'')==='inactive'?'selected':''?>>غیرفعال</option></select></div><div class="col-12"><button class="btn btn-primary btn-lg">ذخیره</button><a class="btn btn-light" href="?section=<?=e($section)?>">انصراف</a></div></form><?php endif; ?>
<div class="table-responsive mt-4"><table class="table align-middle"><thead><tr><th>ردیف</th><th>عنوان</th><th>وضعیت</th><th>ترتیب</th><th>عملیات</th></tr></thead><tbody><?php foreach($filtered as $it): ?><tr><td><?=e($it['id']??'')?></td><td><strong><?=e($it['title']??$it['name']??$it['question']??$it['internal_title']??'-')?></strong></td><td><?=render_status_badge($it['status']??'active')?></td><td><?=e($it['sort_order']??0)?></td><td><a class="btn btn-sm btn-outline-primary" href="?section=<?=e($section)?>&id=<?=e($it['id']??0)?>&action=edit">ویرایش/جزئیات</a><form method="post" class="d-inline" onsubmit="return confirm('حذف شود؟')"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><input type="hidden" name="delete_id" value="<?=e($it['id']??0)?>"><button class="btn btn-sm btn-outline-danger">حذف</button></form></td></tr><?php endforeach; ?></tbody></table></div></section>
<?php admin_footer(); ?>
